### ISSUE TITLE
New repo name?

### ISSUE THREAD

**Issue by SethTisue** [lampepfl/async#15]
Martin says “async” is a temporary, placeholder name, but what will it change to?

(one motivation, I think, is to avoid any confusion with https://github.com/scala/scala-async and/or https://github.com/rssh/dotty-cps-async)

**Comment by He-Pin** [comment]
fiber

**Comment by natsukagami** [comment]
We will soon be changing it to `gears` :)

**Comment by He-Pin** [comment]
> We will soon be changing it to `gears` :) 

Radiation ，wow, looking forward for feature update.
